# 개발 서버 환경 설정
spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://${DB_HOST:dev-mysql-server}:${DB_PORT:3306}/${DB_NAME:fintech_platform}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:fintech123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      validation-timeout: 3000
      leak-detection-threshold: 60000
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate  # 개발 서버에서는 스키마 검증만
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:dev-redis-server}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

# 로깅 설정
logging:
  level:
    com.fintech.platform: INFO
    org.springframework.data.redis: INFO
    org.redisson: INFO
    org.hibernate.SQL: INFO
    root: INFO
  file:
    name: logs/fintech-platform-dev.log
    max-size: 100MB
    max-history: 30

# 보안 설정
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
